# The problem input describes all of the possible
# replacements and, at the bottom, the medicine
# molecule used to calibrate the machine. Using
# the starting molecule, a series of replacements
# can be performed, one per step, generating new
# molecules. The machine replaces without regard
# for the surrounding characters. For example,
# given the string H2O, the transition H => OO
# would result in OO2O.
#
# How many distinct molecules can be created after
# all the different ways you can perform one
# replacement on the medicine molecule?

import time          # For timing the execution

# Read in the data file and convert it to a list
# of strings.
def readFile(filename):
   lines = []
   try:
      with open(filename, "r") as file:
         line = file.readline()
         while line:
            lines.append(line.replace('\n', ''))
            line = file.readline()

         file.close()
            
   except FileNotFoundError:
      print("Error: File not found!")
   except:
      print("Error: Can't read from file!")

   # Only need the first number (as a string).
   return lines



# Take the file input and convert it to the
# starting molecule (the last line of the file
# input) and a dictionary of lists for the
# replacement rules. Each key in the dictionary
# can be replaced by on of the values in the
# corresponding list.
def parseInput(values):
   # Pull out the starting molecule.
   start = values[-1]

   # Generate the dictionary of replacements.
   replacements = dict()
   for rule in values[:-2]:
      parts = rule.split()
      if parts[0] not in replacements:
         replacements[parts[0]] = list()
      replacements[parts[0]].append(parts[2])

   # Return the start and replacement rules.
   return (start, replacements)



if __name__ == '__main__':
   # Start the timer
   start_time = time.time()

   # Retrieve the data from the input file and
   # convert it into the starting molecule string
   # and a dictionary of replacement rules.
   file_input = readFile("input19b.txt")
   start, replacements = parseInput(file_input)

   # New molecules need to be stored in a set to
   # handle duplicates.
   molecules = set()

   # Iterate through each character of the
   # starting molecule.
   for i in range(len(start)):
      # If a match is found for any replacement
      # rule, then generate a new molecule.
      for key in replacements:
         # Make sure that the remaining length of
         # the starting molecule can support the
         # given key.
         if (i + len(key)) <= len(start):
            # Calculate the ending index of the
            # key in the molecule.
            j = i+len(key)
            # Is it a match?
            if start[i:j] == key:
               # If so, then replace it for each
               # of the replacement values.
               for r in replacements[key]:
                  # Concatenation depending on
                  # location of replacement.
                  if i == 0:
                     molecules.add(r + start[j:])
                  elif i == len(start):
                     molecules.add(start[:i] + r)
                  else:
                     molecules.add(start[:i] + r + start[j:])
      
   # Display the total number of molecules
   # generated by the replacement rules.
   print('Number of molecules = ' + str(len(molecules)))

   # Stop the timer and print the execution time.
   print("\n\n--- %s seconds ---" % (time.time() - start_time))
